dist: trusty
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: 
  - "sudo apt-get -y update"
  - "sudo apt-get install -y git python-gobject ninja python3-cairosvg python3-gi python3-pip python-dev intltool gobject-introspection"
  - "pip3 install requests Pillow meson"
  - "git clone https://github.com/bil-elmoussaoui/Icon-Requests && cd ./Icon-Requests && mkdir build && cd ./build && meson .. && ninja && ninja install"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
script: icon-requests --debug
